### ISSUE TITLE
The plugin `external_app_launcher` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by endritgojanikodelabs** [GeekyAnts/external_app_launcher#1]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by sarika01** [comment]
The support for Android V2 embedding is now available in external_app_launcher: ^2.0.2
