### ISSUE TITLE
Keep showing me : cant find the app installed and takes me to playstore. 

### ISSUE THREAD

**Issue by sahalkabeer** [GeekyAnts/external_app_launcher#10]
I tried using Android Emulator and a Physical device too

**Comment by sahalkabeer** [comment]
I tried different package names , nothing works.
But then i added a line to check if app is installed first, then called launchapp function and it worked.
But i am not sure what solved the problem

**Comment by rusyadi36** [comment]
Starting with Android 11 need  to declare `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`  to your AndroidManifest.xml

**Comment by Gayathri-GA** [comment]
The support is now available in external_app_launcher: ^3.0.0
