### ISSUE TITLE
Directly open Google Play even using openStore: false

### ISSUE THREAD

**Issue by lmta1** [GeekyAnts/external_app_launcher#11]
Hi, I'm having trouble using your package. Following your documentation, I have used:

await LaunchApp.isAppInstalled(androidPackageName: 'xxxxxxx');

I have used different apps to see if they were saved and in all cases the result has been false.

I'm sure I spelled the package name right because with the LaunchApp.openApp method, it opens the correct page on google play to install the app I'm trying to open with the package.

I have also tried to find packages like com.chrome.android, also being installed as the one I try to open.

**Comment by hemanthkb97** [comment]
hello @lmta1, can you give code sample you have used and also try once in real device and see if you have same issue

**Comment by TusharFA** [comment]
Facing the same issue. 

 final isAppInstalled = await LaunchApp.isAppInstalled(
                            androidPackageName: 'com.app.debug'
                        );

It's always returning false and redirecting to playstore even though the app is installed on the phone.
Package name is correct, rechecked multiple times.
Checked on real device and emulator both. Working fine for iOS.

**Comment by vd-37** [comment]
Facing the same issue, did you guys find any solution @lmta1 @TusharFA?

**Comment by DanielHoltebo** [comment]
@vd-37 @TusharFA  @lmta1 got it to work on my device by adding some parameters inside my AndroidManifest.xml:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_application">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />       <--- added this
   <application
.
.
.
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
        <category android:name="android.intent.category.HOME"/>          <--- added this
        <category android:name="android.intent.category.DEFAULT"/>       <--- added this
    </intent-filter>

**Comment by shubhamvermaa** [comment]
god bro!!

**Comment by mehmetpeker** [comment]
> @vd-37 @TusharFA @lmta1 got it to work on my device by adding some parameters inside my AndroidManifest.xml:
> 
> ```
>     package="com.example.flutter_application">
>     <uses-permission android:name="android.permission.INTERNET"/>
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
>     <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />       <--- added this
>    <application
> .
> .
> .
>     <intent-filter>
>         <action android:name="android.intent.action.MAIN"/>
>         <category android:name="android.intent.category.LAUNCHER"/>
>         <category android:name="android.intent.category.HOME"/>          <--- added this
>         <category android:name="android.intent.category.DEFAULT"/>       <--- added this
>     </intent-filter>```
> ```

this solved my problem thanks
