### ISSUE TITLE
app store link not working

### ISSUE THREAD

**Issue by shashikiran918** [GeekyAnts/external_app_launcher#21]
this is my code

void launchApp() async {
  var openAppResult = await LaunchApp.openApp(
    androidPackageName: 'com.example.zoom_demo',
    appStoreLink:
        'https://play.google.com/store/apps/details?id=com.aceenggacademy.mobile',
  );
}
when external app is not available in device it should redirect to store right ! but in my code it is  redirecting to playstore and still loading like circular progress indicator not showing  app store link  play store page .

This is my androidmanifestxml file 

![Screenshot from 2022-08-10 16-21-25](https://user-images.githubusercontent.com/85386298/183884306-1ebcadb0-1ad5-4d9c-9f46-7e25c555ca7c.png)

can u please help me to find this app store link problem?

**Comment by Gayathri-GA** [comment]
Hi @shashikiran918 
You are specifying google play store link instead of passing App Store link.
In order to open your app on App Store,You should declare variables as below

appStoreLink:'itms-apps://itunes.apple.com/us/app/ace-engineering-academy/id1039063761',

**Comment by shashikiran918** [comment]
ya but u given apple appstore link but how to open in android google play store for same above link with id

**Comment by shashikiran918** [comment]
thank you got it
