### ISSUE TITLE
app build issue with external_app_launcher package

### ISSUE THREAD

**Issue by erenmalkoc** [GeekyAnts/external_app_launcher#40]
Execution failed for task ':external_app_launcher:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: C:\Users\\IdeaProjects\my_app\build\external_app_launcher\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

I've tried:

 -upgrading the Android SDK version
 -downgrading the package version

none of these worked.

**Comment by rbernadev** [comment]
i find a workaround @erenmalkoc 

Goto the android studio external libraries in the left side
--> select the library external_app_launcher
--> then goto the android -> build.gradle and update the compileSdkVersion to 34

**Comment by erenmalkoc** [comment]
thanks.  it worked

**Comment by josephmangmang** [comment]
why close? 
can we fix inside the library?

**Comment by josephmangmang** [comment]
flutter build apk --release   is not working

**Comment by yeras-is** [comment]
@erenmalkoc  library throws this issue when we're building APK, for AAB works fine, yet we still need support of release APK build

**Comment by Suheb786** [comment]
ios builds working i think issue is in only apk release build Please update if any solution found 
i already have  
compileSdkVersion 34
flutter version 3.24.0
external_app_launcher: 4.0.0
