### ISSUE TITLE
What is the use of "LaunchVpnPlugin.java" class?

### ISSUE THREAD

**Issue by AliAkberAakash** [GeekyAnts/external_app_launcher#6]
This is not an issue more like a query. I was studying the internals of this library and I needed to make some changes. I found two classes : `LaunchVpnPlugin.java` and `LaunchExternalappPlugin.java` . I made changes to  `LaunchExternalappPlugin.java` and got my desired output, I was wondering why `LaunchVpnPlugin.java` exists?

**Comment by sarika01** [comment]
It is redundant code.
